### ISSUE TITLE
bot doesnt actually buy or sell anything.

### ISSUE THREAD

**Issue by xHypn13245** [Avnsx/EFT_Flea_Market_Bot#10]
Everytime i run the bot it just says it bought something waited x amount of time before purchasing and then will say the same thing about a different item next , it never actually purchases any of the items.
"
[LOG:] Bought 5bc9be8fd4351e00334cae6e [ item_barter_other_tea ] at 14500 / 20815
  Waited 0.3979831266403198 Seconds before purchase

[LOG:] Bought 5d1b39a386f774252339976f [ item_barter_building_silicontube ] at 10000 / 14175
  Waited 0.5372608637809754 Seconds before purchase

[INFO:] Next Iteration with token: 
     Wishlist currently includes: 317 items!"

**Comment by Avnsx** [comment]
The reason it's not buying shit is because it errors out, you do not see the error output because i've silenced it to provide a smooth enviroment. It's one of these error codes: 228, 1512, 1514, 1500 that hold you back from buying items. This might be an temporary time limitation or your account level might be too low. You might've even not even unlocked flea market by not being atleast level 10. You can search each of these error codes up on the internet yourself by typing in the error code number + escape from tarkov.

It's very likely that you're experiencing error 1500 as you've stated in the issue ticket before https://github.com/Avnsx/EFT_Flea_Market_Bot/issues/9

Nothing else I can do for you in this case
